---

metricbeat_cosmos_node_port: 26657
metricbeat_cosmos_node_host: localhost
metricbeat_cosmos_node_enabled: true
metricbeat_cosmos_template:
  - src: cosmos.yml.j2
    dest: "{{ metricbeat_module_path }}/cosmos.yml"
    owner: "{{ metricbeat_owner }}"
    group: "{{ metricbeat_group }}"
    mode: "0640"
