---
elasticsearch_port: 9200

elasticsearch_templates:
  - src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml


elasticsearch_other_nodes: "{{ elasticsearch_unicast_hosts | difference(elasticsearch_exclude_node) }}"

elasticsearch_exclude_node:
 - "{{ ansible_host }}"

elasticsearch_unicast_hosts: "{{ groups['es'] | map('extract', hostvars, ['ansible_host']) | list }}"

## Logical Volume / Volume Group
elasticsearch_filesystem_list:
  - lv: lv_es_data
    vg: fedora_fedora
    size: 50g
    path: "{{ elasticsearch_path_data }}"
    owner: elasticsearch
    group: elasticsearch
    mode: "0750"
    fstype: "{{ filesystem_type | default('xfs') }}"
    force: false
    shrink: false

  - lv: lv_es_log
    vg: fedora_fedora
    size: 500M
    path: "{{ elasticsearch_path_logs }}"
    owner: elasticsearch
    group: elasticsearch
    mode: "0750"
    fstype: "{{ filesystem_type | default('xfs') }}"
    force: false
    shrink: false

elasticsearch_protocol: https
elasticsearch_host: "{{ ansible_host }}"
elasticsearch_ssl_protocols: TLSv1.2

elasticsearch_users_custom:
  - name: grafana
    content: "{{ lookup('template', 'user/grafana.json.j2') }}"
  - name: minotor
    content: "{{ lookup('template', 'user/minotor.json.j2') }}"
  - name: metricbeat
    content: "{{ lookup('template', 'user/metricbeat.json.j2') }}"
  - name: mozquito
    content: "{{ lookup('template', 'user/metricbeat.json.j2') }}"

elasticsearch_roles_custom:
  - name: grafana
    content: "{{ lookup('template', 'role/grafana.json.j2') }}"
  - name: minotor
    content: "{{ lookup('template', 'role/minotor.json.j2') }}"
  - name: metricbeat
    content: "{{ lookup('template', 'role/metricbeat.json.j2') }}"