---
haproxy_package: haproxy-2.4.7

haproxy_config_folder: /etc/haproxy

haproxy_templates: "{{ haproxy_default_templates }}"

haproxy_default_templates:
  - src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0640"
    owner: haproxy
    group: haproxy
  - src: haproxy/00_haproxy.cfg.j2
    dest: "{{ haproxy_config_folder }}/00_haproxy.cfg"
    mode: "0640"
    owner: haproxy
    group: haproxy
  - src: haproxy/01_stats.cfg.j2
    dest: "{{ haproxy_config_folder }}/01_stats.cfg"
    mode: "0640"
    owner: haproxy
    group: haproxy

haproxy_maxconn: "{{ ansible_processor_vcpus * 2000 }}"

haproxy_socket: /var/run/haproxy.sock level admin

haproxy_mng_ip: 0.0.0.0
haproxy_mng_port: 9090
haproxy_mng_user: admin
haproxy_mng_psw: "{{ haproxy_admin_password }}"

haproxy_certs_path: /etc/pki/tls/certs

haproxy_log_dir: /var/log/haproxy
haproxy_log_size: 1G