---
kibana_elasticsearch_url: >-
  {% set comma = joiner(",") %}{% for host in groups['elasticsearch'] %}{{ comma() }}"https://{{ hostvars[host]['ansible_host'] }}:9200"{% endfor %}

ssl_minimal_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: /etc/kibana/cert.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: /etc/kibana/chain.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: /etc/kibana/fullchain.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: /etc/kibana/privkey.pem
    user: kibana

