---
kibana_custom_templates:
  - src: kibana/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: "0640"

kibana_data_dir: /var/lib/kibana
kibana_share_dir: /usr/share/kibana
kibana_log_dir: /var/log/kibana
kibana_pid_dir: /var/run/kibana

kibana_custom_dirs:
  - path: "{{ kibana_pid_dir }}"
    state: directory
    owner: kibana
    group: kibana
    mode: "0755"
  - path: "{{ kibana_log_dir }}"
    state: directory
    owner: kibana
    group: kibana
    mode: "0750"

# Filesystem
kibana_data_size: 1G
kibana_share_size: 1536M
kibana_log_size: 1G

kibana_filesystem_list:
  - lv: lv_kibana_data
    vg: fedora_fedora
    size: "{{ kibana_data_size }}"
    path: "{{ kibana_data_dir }}"
    owner: kibana
    group: kibana
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - lv: lv_kibana_share
    vg: fedora_fedora
    size: "{{ kibana_share_size }}"
    path: "{{ kibana_share_dir }}"
    owner: kibana
    group: kibana
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - lv: lv_kibana_log
    vg: fedora_fedora
    size: "{{ kibana_log_size }}"
    path: "{{ kibana_log_dir }}"
    owner: kibana
    group: kibana
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

kibana_elasticsearch_username: kibana_system

kibana_ssl_protocols: "TLSv1.2"

kibana_elasticsearch_url: >-
  {% set comma = joiner(",") %}{% for host in groups['elasticsearch'] %}{{ comma() }}"https://{{ hostvars[host]['ansible_host'] }}:9200"{% endfor %}

ssl_minimal_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: /etc/kibana/cert.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: /etc/kibana/chain.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: /etc/kibana/fullchain.pem
    user: kibana
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: /etc/kibana/privkey.pem
    user: kibana

