galaxy_info:
  author: Douceur
  description: this role install & configure generic cosmos full node

  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
   - name: Ubuntu
     versions:
     - 22
     - 23

  galaxy_tags: ['blockhain', 'cosmos', 'validator', 'full-node']

dependencies: []



# Define the variables that should be present
vars:
  - name: cosmos_node_factory_git_version
    type: string
  - name: cosmos_node_factory_binaries_download_url
    type: string
  - name: cosmos_node_factory_genesis_donwload_url
    type: string
  - name: cosmos_node_factory_seeds
    type: string
  - name: cosmos_node_factory_persistent_peers
    type: string
  - name: cosmos_node_factory_chain_id
    type: string
  - name: cosmos_node_factory_binaries
    type: string
  - name: cosmos_node_factory_denom
    type: string
  - name: cosmos_node_factory_database_backend
    type: string

# Use the assert module to check the presence of variables
pre_tasks:
  - name: Check if required variables are present
    assert:
      that:
        - cosmos_node_factory_git_version is defined
        - cosmos_node_factory_binaries_download_url is defined
        - cosmos_node_factory_genesis_donwload_url is defined
        - cosmos_node_factory_seeds is defined
        - cosmos_node_factory_persistent_peers is defined
        - cosmos_node_factory_chain_id is defined
        - cosmos_node_factory_binaries is defined
        - cosmos_node_factory_denom is defined
        - cosmos_node_factory_database_backend is defined
      fail_msg: "One or more required variables are missing."