---

elasticsearch_grafana_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/grafana:moz ' ~ hashi_connect) }}"
elasticsearch_metricbeat_password: "{{ lookup('auto_pass', hashi_elasticsearch_path ~ '/metricbeat:moz') }}"
elasticsearch_free_metricbeat_password: "{{ lookup('auto_pass', hashi_elasticsearch_path ~ '/free_metricbeat:moz') }}"

elasticsearch_custom_users:
  - name: grafana
    password: "{{ elasticsearch_grafana_password }}"
    roles: [grafana_role]
    full_name: grafana user from olympus
  - name: metricbeat_olympus
    password: "{{ elasticsearch_metricbeat_password }}"
    roles: [metricbeat_olympus]
    full_name: metricbeat user from olympus
  - name: free_metricbeat
    password: "{{ elasticsearch_free_metricbeat_password }}"
    roles: [metricbeat_role]
    full_name: metricbeat_ext user from olympus


elasticsearch_custom_roles:
  - name: metricbeat_olympus
    cluster_settings: [manage_index_templates, monitor, manage_ilm]
    indices:
      - names: [metricbeat*, .monitoring*, .ds-.monitoring-*]
        privileges: [ write, create_index, manage, view_index_metadata ]

  - name: free_metricbeat
    cluster_settings: []
    indices:
      - names: [metricbeat*]
        privileges: [ write, create_index, manage, view_index_metadata ]

  - name: grafana
    cluster_settings: []
    indices:
      - names: [flux-*, cosmos-*, defi-*, minotor-*, metricbeat*, .monitoring-*, osmosis-*]
        privileges: [ read, monitor, view_index_metadata ]
