---

elasticsearch_grafana_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/grafana:moz ' ~ hashi_connect) }}"
elasticsearch_metricbeat_password: "{{ lookup('auto_pass', 'elasticsearch/metricbeat', key='moz') }}"
elasticsearch_free_metricbeat_password: "{{ lookup('auto_pass', 'elasticsearch/free_metricbeat', key='moz') }}"
elasticsearch_filebeat_password: "{{ lookup('auto_pass', 'elasticsearch/filebeat', key='moz') }}"
elasticsearch_free_filebeat_password: "{{ lookup('auto_pass', 'elasticsearch/free_filebeat', key='moz') }}"


elasticsearch_custom_users:
  - name: grafana
    password: "{{ elasticsearch_grafana_password }}"
    roles: [grafana]
    full_name: grafana user from olympus
  - name: metricbeat_olympus
    password: "{{ elasticsearch_metricbeat_password }}"
    roles: [metricbeat_olympus]
    full_name: metricbeat user from olympus
  - name: free_metricbeat
    password: "{{ elasticsearch_free_metricbeat_password }}"
    roles: [free_metricbeat]
    full_name: metricbeat_ext user from olympus
  - name: filebeat_olympus
    password: "{{ elasticsearch_filebeat_password }}"
    roles: [filebeat_olympus]
    full_name: filebeat user from olympus
  - name: free_filebeat
    password: "{{ elasticsearch_free_filebeat_password }}"
    roles: [free_filebeat]
    full_name: filebeat_ext user from olympus

elasticsearch_custom_roles:
  - name: metricbeat_olympus
    cluster_settings: [manage_index_templates, monitor, manage_ilm]
    indices:
      - names: [metricbeat*, .monitoring*, .ds-.monitoring-*]
        privileges: [ write, create_index, manage, view_index_metadata ]

  - name: free_metricbeat
    cluster_settings: [monitor, manage_index_templates, manage_ilm]
    indices:
      - names: [metricbeat*]
        privileges: [ write, create_index, manage, view_index_metadata ]

  - name: grafana
    cluster_settings: []
    indices:
      - names: [flux-*, cosmos-*, defi-*, minotor-*, metricbeat*, .monitoring-*, osmosis-*]
        privileges: [ read, monitor, view_index_metadata ]

  - name: filebeat_olympus
    cluster_settings: [manage_index_templates, monitor, manage_ilm]
    indices:
      - names: [filebeat*, .monitoring*, .ds-.monitoring-*]
        privileges: [ write, create_index, manage, view_index_metadata ]

  - name: free_filebeat
    cluster_settings: [monitor, manage_index_templates, manage_ilm]
    indices:
      - names: [filebeat*]
        privileges: [ write, create_index, manage, view_index_metadata ]
