---
metricbeat_elasticsearch_user: metricbeat_olympus
metricbeat_elasticsearch_password: "{{ elasticsearch_metricbeat_password }}"
metricbeat_custom_templates:
  - src: elasticsearch-xpack.yml.j2
    dest: /etc/metricbeat/modules.d/elasticsearch-xpack.yml
  - src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  - src: system.yml.j2
    dest: /etc/metricbeat/modules.d/system.yml