---
certbot_owner: root
certbot_group: certbot

certbot_root_dir: /opt/certbot
certbot_cred_path: "{{ certbot_root_dir }}/certbot.cred"

certbot_final_name_pattern: "{{ ansible_fqdn }}"

certbot_directories:
  - path: /opt/certbot

certbot_templates:
  - src: certbot.sh.j2
    dest: "{{ certbot_root_dir }}/certbot.sh"
  - src: certbot.cred.j2
    dest: "{{ certbot_cred_path }}"

certbot_credential: "{{ lookup('hashi_vault', hashi_certbot_path ~ '/ovh ' ~ hashi_connect) }}"

certbot_link_to_create:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: "/etc/ssl/certs/{{ certbot_final_name_pattern }}.cert.pem"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: "/etc/ssl/certs/{{ certbot_final_name_pattern }}.chain.pem"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: "/etc/ssl/certs/{{ certbot_final_name_pattern }}.fullchain.pem"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: "/etc/ssl/certs/{{ certbot_final_name_pattern }}.privkey.pem"
