---
custom_vg_name: olympus

subspace_node_install_enabled: true
subspace_node_filesystem_enabled: true
subspace_node_p2p_port: 60333
subspace_node_dsn_port: 60433

subspace_node_filesystem_list:
  - lv: lv_chimera
    vg: "{{ custom_vg_name }}"
    size: 1g
    path: "{{ subspace_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
  - disk: sdb
    path: "{{ subspace_node_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    direct_mount: true

  - lv: lv_subspace_node_log
    vg: "{{ custom_vg_name }}"
    size: 1g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs


subspace_operator_install_enabled: false
subspace_operator_filesystem_enabled: false

subspace_farmer_install_enabled: true
subspace_farmer_filesystem_enable: true

subspace_farmer_port: 60533
subspace_farmer_disks: []




