
---

subspace_node_install_enabled: true
subspace_node_filesystem_enabled: true

subspace_operator_install_enabled: false
subspace_operator_filesystem_enabled: false

subspace_farmer_install_enabled: true
subspace_farmer_filesystem_enable: true

subspace_farmer_disks: []




