---
elasticsearch_owner: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_service_name: elasticsearch
elasticsearch_path_logs: /var/log/elasticsearch
elasticsearch_http_base_url: "{{ elasticsearch_protocol }}://{{ elasticsearch_host }}:{{ elasticsearch_port }}"
elasticsearch_elastic_user: elastic
elasticsearch_kibana_user: kibana
elasticsearch_url_license: "{{ elasticsearch_http_base_url }}/_license"
elasticsearch_url_security: "{{ elasticsearch_http_base_url }}/_security"
elasticsearch_path_data: /var/lib/elasticsearch
elasticsearch_path_bin: /usr/share/elasticsearch

elasticsearch_version: "{{ elk_version }}"

elasticsearch_rpms:
  - "elasticsearch-{{ elasticsearch_version }}"

elasticsearch_path_config: /etc/elasticsearch

elasticsearch_elastic_current_password:

elasticsearch_cluster_users:
  - name: kibana_system
    password: "{{ elasticsearch_kibana_password }}"
  - name: elastic
    password: "{{ elasticsearch_elastic_password }}"

elasticsearch_custom_users:
  - name: grafana
    password: "{{ elasticsearch_grafana_password }}"
    role: [grafana_role]
  - name: minotor
    password: "{{ elasticsearch_minotor_password }}"
    role: [minotor_writer]

ssl_minimal_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: /etc/elasticsearch/cert.pem
    user: elasticsearch
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: /etc/elasticsearch/chain.pem
    user: elasticsearch
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: /etc/elasticsearch/fullchain.pem
    user: elasticsearch
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: /etc/elasticsearch/privkey.pem
    user: elasticsearch