---
elasticsearch_path_data: /var/lib/elasticsearch
elasticsearch_path_bin: /usr/share/elasticsearch

elasticsearch_version: "{{ elk_version }}"

elasticsearch_rpms:
  - "elasticsearch-{{ elasticsearch_version }}"


elasticsearch_path_config: /etc/elasticsearch

elasticsearch_elastic_current_password:

elasticsearch_cluster_users:
  - name: kibana_system
    password: "{{ elasticsearch_kibana_password }}"
  - name: elastic
    password: "{{ elasticsearch_elastic_password }}"
  - name: grafana
    password: "{{ elasticsearch_grafana_password }}"
  - name: minotor
    password: "{{ elasticsearch_minotor_password }}"
