---
- name: Ensure CHIA_ROOT is set in .bashrc
  become: true
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bashrc"
    regexp: '^export CHIA_ROOT='
    line: "export CHIA_ROOT={{ chia_root }}"
  loop: "{{ chia_bashrc_editable }}"

- name: Create directory
  become: true
  become_method: "{{ custom_become_method }}"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(chia_owner) }}"
    group: "{{ item.group | default(chia_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ chia_directory }} "

- name: Install binaries
  become: true
  become_method: "{{ custom_become_method }}"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ chia_packages }}"

- name: Fetch remote bdd
  uri:
    url: "{{ chia_db_remote_source }}"
    method: GET
    status_code: 200
    body_format: json
  when: "{{ chia_db_remote_fetch_enabled }}"

- name: Add Keys
  become: true
  become_user: "{{ chia_owner }}"
  no_log: true
  ansible.builtin.shell: |
    echo "{{ item }}" | chia keys add -l ""
  environment:
    CHIA_ROOT: "{{ chia_root }}"
  when:
    - keys | length
  with_items: "{{ keys }}"