---
- name: passe nonlocal_bind à 1 dans sysctl
  become: true
  become_method: "{{ custom_become_method }}"
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
    reload: yes

- name: création de répertoires additionnels de configuration
  become: true
  become_method: "{{ custom_become_method }}"
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(600) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ haproxy_additional_config_dirs }}"
  notify: haproxy_need_restart

- name: Gestion haproxy multifile
  block:
    - name: "liste les fichiers .cfg présents dans {{ haproxy_config_folder }}"
      find:
        paths: "{{ haproxy_config_folder }}/"
        patterns: "*.cfg"
      register: haproxy_existing_config_files

    - name: "Supprime les fichiers .cfg non déclarés dans Ansible"
      file:
        state: absent
        path: "{{ haproxy_config_folder }}/{{ item }}"
      loop: "{{ haproxy_existing_config_files.files | map(attribute='path') | list | difference(haproxy_templates_filedest) }}"
  become: true
  become_method: "{{ custom_become_method }}"
  when: haproxy_templates | length > 1

- name: création des fichiers de configuration haproxy
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(600) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ haproxy_templates }}"
  notify: haproxy_need_restart

- name: configurations additionnelles nécessitant un redémarrage du service
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(600) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ haproxy_config_files }}"
  notify:
    - haproxy_need_restart
