---
- name: install haproxy packges
  become: true
  become_method: "{{ custom_become_method }}"
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ haproxy_packages }}"
  notify:
    - haproxy_need_restart


