---

subspace_node_p2p_port: 40333
subspace_node_dsn_port: 40433

subspace_node_filesystem_list:
  - disk: sdb
    path: "{{ subspace_node_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    direct_mount: true

  - lv: lv_subspace_node_log
    vg: "{{ custom_vg_name }}"
    size: 1g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"

subspace_farmer_port: 40533
subspace_farmer_disks:
  - path=/mnt/subspace_001/hydras_alpha_fikwot4T_baie_top_left/alpha,size=3.7T




