---
- name: Templatise le fichier repo
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root

- name: installation
  become: true
  become_method: "{{ custom_become_method }}"
  yum:
    name: grafana
    state: present

- name: Restreint le umask du service à 0027
  become: true
  become_method: "{{ custom_become_method }}"
  block:
    - name: crée le dossier grafana.service.d
      file:
        path: /etc/systemd/system/grafana-server.service.d
        state: directory
    - name: copie les paramètres de umask
      copy:
        dest: /etc/systemd/system/grafana-server.service.d/grafana-server.conf
        src: grafana-server.conf

- name: Copy ssl files
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "{{ item.mode | default('0640') }}"
    remote_src: true
  loop: "{{ ssl_minimal_file }}"

- name: configuration
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(grafana_owner) }}"
    group: "{{ item.group | default(grafana_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ grafana_custom_configs }}"
  when: grafana_custom_configs is defined
  notify: grafana_need_restart
