---
- name: Restart hddtemp
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: hddtemp  
    state: restarted
    enabled: true
    daemon_reload: true
  listen: hddtemp_need_restart
