---

- ansible.builtin.import_playbook: playbook_prepare.yml
- ansible.builtin.import_playbook: playbook_certbot.yml

- ansible.builtin.import_playbook: playbook_vault.yml
- ansible.builtin.import_playbook: playbook_elasticsearch.yml
- ansible.builtin.import_playbook: playbook_kibana.yml
- ansible.builtin.import_playbook: playbook_haproxy.yml
- ansible.builtin.import_playbook: playbook_grafana.yml
- ansible.builtin.import_playbook: playbook_proxmox.yml

- ansible.builtin.import_playbook: playbook_subspace.yml
- ansible.builtin.import_playbook: playbook_streamr.yml

- ansible.builtin.import_playbook: playbook_metricbeat.yml

