---
- hosts: localhost
  pre_task:
    - name: Generate local hosts templates
      gather_facts: no
      become: true
      become_method: "{{ custom_become_method }}"
      template:
        src: hosts.j2
        dest: /etc/hosts

- hosts: olympus
  roles:
    - role: prepare
  tags:
    - prepare

