---
#==================================================================
# GRAFANA
#==================================================================
- hosts: mermaid
  tags:
    - grafana
  roles:
    - role: tocard.utils.grafana
