---
## --------------------------------------------------------------------
## Metricbeat
## --------------------------------------------------------------------
- hosts: olympus
  tags:
    - filebeat
  roles:
    - role: tocard.utils.filebeat


