
---
#==================================================================
# Streamr
#==================================================================
- hosts: streamr
  serial: 1  # Set serial to 1 for sequential execution
  roles:
    - role: tocard.utils.streamr
      streamr_virtual_group_name: "{{ custom_vg_name }}"
      tags:
        - streamr
  vars:
    streamr_delay_minutes: 3
  tasks:
    - name: Pause for 3 minutes
      pause:
        minutes: "{{ streamr_delay_minutes }}"