---
#==================================================================
# Subspace Automatic Deployment
#==================================================================
- hosts: subspace
  tags:
    - subspace
  roles:
    - role: tocard.utils.subspace
      subspace_farmer_install_enabled: false
    - role: tocard.utils.nats
    - role: tocard.utils.subspace_controller
