---

#==================================================================
# CERTBOT
#==================================================================
- hosts: olympus
  roles:
    - role: tocard.utils.certbot
      tags:
        - certbot


