---
## --------------------------------------------------------------------
## Metricbeat
## --------------------------------------------------------------------
- hosts: olympus
  tags:
    - metricbeat
  roles:
    - role: tocard.utils.metricbeat


