---
## --------------------------------------------------------------------
## Metricbeat
## --------------------------------------------------------------------
- hosts: metricbeat
  tags:
    - metricbeat
  roles:
    - role: tocard.utils.filesystem
      filesystem_list: "{{ metricbeat_filesystem_list }}"
    - role: metricbeat


