---
#==================================================================
# Chimera-Juno
#==================================================================
- hosts: chimera
  roles:
    - role: user
      user_name: "{{ babylon_node_owner }}"
      user_group: "{{ babylon_node_group }}"
      tags:
        - user
        - filesystem
        - babylon
    - role: filesystem
      filesystem_list: "{{ babylon_node_filesystem_list }}"
      tags:
        - filesystem
        - babylon
    - role: install_go
      golang_version: '1.19.0'
      golang_install_dir: '/opt/go/babylon'
    - role: babylon_node
      tags:
        - babylon
