---
#==================================================================
# HAPROXY
#==================================================================
- hosts: pegasus:hermes
  tags:
    - haproxy
  roles:
    - role: tocard.utils.haproxy

