
---
#==================================================================
# Streamr
#==================================================================
- hosts: streamr
  serial: 1
  roles:
    - role: tocard.utils.streamr
      streamr_virtual_group_name: "{{ custom_vg_name }}"
      streamr_serial_mode_enabled: true
      tags:
        - streamr
