---

#==================================================================
# CERTBOT
#==================================================================
- hosts: certbot
  tags:
    - certbot
  roles:
    - role: tocard.utils.certbot



