---
## --------------------------------------------------------------------
## vault
## --------------------------------------------------------------------
- hosts: basilisk
  tags:
    - vault
  roles:
    - role: tocard.utils.vault


