---
- name: Prepare pi-hole
  hosts: hades
  gather_facts: false
  tasks:
  - name: Generate local hosts templates
    become: true
    template:
      src: hosts.j2
      dest: /etc/pihole/custom.list

- hosts: olympus
  roles:
    - role: prepare
  tags:
    - prepare

