---
## --------------------------------------------------------------------
## Elasticsearch
## --------------------------------------------------------------------
- hosts: cerberus
  tags:
    - elasticsearch
  roles:
    - role: tocard.utils.elasticsearch
