---
#==================================================================
# Ternoa Automatic Deployment
#==================================================================
- hosts: ternoa
  roles:
    - role: tocard.utils.ternoa
      tags:
        - ternoa

