---
#==================================================================
# HAPROXY
#==================================================================
- hosts: haproxy
  roles:
    - role: user
      user_name: haproxy
      user_group: haproxy
    - role: filesystem
      filesystem_list: "{{ haproxy_filesystem_list }}"
      tags:
        - filesystem
        - haproxy
    - role: haproxy
      tags:
        - haproxy
