---
#==================================================================
# Chimera-base
#==================================================================
- hosts: chimera
  roles:
    - role: tocard.utils.user
      user_name: chimera
      user_group: chimera
      user_password: "{{ lookup('hashi_vault', hashi_chimera_path ~ '/user:moz ' ~ hashi_connect) }}"
      user_groups: [ "{{ sudo_group }}", certbot]
      tags:
        - chimera_base
    - role: chimera_base
      tags:
        - chimera_base
