---
#==================================================================
# GRAFANA
#==================================================================
- hosts: grafana
  roles:
    - role: user
      user_name: grafana
      user_group: grafana
    - role: filesystem
      filesystem_list: "{{ grafana_filesystem_list }}"
      tags:
        - filesystem
        - grafana
    - role: grafana
      tags:
        - grafana