---
#==================================================================
# Subspace Automatic Deployment
#==================================================================
- hosts: subspace
  tags:
    - subspace
  roles:
    - role: tocard.utils.subspace

