---
#==================================================================
# Subspace Automatic Deployment
#==================================================================
- hosts: subspace
  tags:
    - subspace
  roles:
    - role: tocard.utils.nats
    - role: tocard.utils.subspace_node
    - role: tocard.utils.subspace_controller
    - role: tocard.utils.subspace_cache
    - role: tocard.utils.subspace_farmer
    - role: tocard.utils.subspace_plotter