---
#==================================================================
# Centaur
#==================================================================
- hosts: centaur
  tags:
    - chia
  roles:
    - role: chia_rpc
