---
## --------------------------------------------------------------------
## Elasticsearch
## --------------------------------------------------------------------
- hosts: es
  tags:
    - elasticsearch
  roles:
    - role: user
      user_name: elasticsearch
      user_group: elasticsearch
    - role: filesystem
      filesystem_list: "{{ elasticsearch_filesystem_list }}"
      tags:
        - elasticsearch
    - role: elasticsearch
      tags:
        - elasticsearch

