---

#==================================================================
# CERTBOT
#==================================================================
- hosts: certbot
  roles:
    - role: tocard.utils.certbot
      tags:
        - certbot


