---
## --------------------------------------------------------------------
## Kibana
## --------------------------------------------------------------------
- hosts: mermaid
  tags:
    - kibana
  roles:
    - role: tocard.utils.kibana


