---
## --------------------------------------------------------------------
## vault
## --------------------------------------------------------------------
- hosts: vault
  tags:
    - vault
  roles:
    - role: tocard.utils.vault
      tags:
        - vault

