---
## --------------------------------------------------------------------
## HddTemp
## --------------------------------------------------------------------
- hosts: hddtemp
  tags:
    - hddtemp
  roles:
    - role: hddtemp


