---
#==================================================================
# Subspace Automatic Deployment
#==================================================================
- hosts: subspace
  roles:
    - role: tocard.utils.subspace
      tags:
        - subspace

