---

- hosts: localhost
  tasks:
   - name: Legacy freebox module
     become: true
     freebox:
       app_id: fr.freebox.integration
       app_name: freebox_ansible
       app_version: 0.1
       device_name: ansible_integration
       freebox_url: http://mafreebox.freebox.fr/api/v8
       vault_username: "{{ hashi_user }}"
       vault_password: "{{ hashi_password }}"
       vault_url: https://basilisk-alpha.mythologic.fr:8200
       vault_path: freebox/app_token
       vault_mount_point: "{{ hashi_short_mount_point }}"

   - name: freebox Lease module
     become: true
     freebox_dhcp:
       app_id: fr.freebox.integration
       app_name: freebox_ansible
       app_version: 0.1
       device_name: ansible_integration
       freebox_url: http://mafreebox.freebox.fr/api/v8
       vault_username: "{{ hashi_user }}"
       vault_password: "{{ hashi_password }}"
       vault_url: https://basilisk-alpha.mythologic.fr:8200
       vault_path: freebox/app_token
       vault_mount_point: "{{ hashi_short_mount_point }}"

   - name: freebox Port module
     become: true
     freebox_port:
       app_id: fr.freebox.integration
       app_name: freebox_ansible
       app_version: 0.1
       device_name: ansible_integration
       freebox_url: http://mafreebox.freebox.fr/api/v8
       vault_username: "{{ hashi_user }}"
       vault_password: "{{ hashi_password }}"
       vault_url: https://basilisk-alpha.mythologic.fr:8200
       vault_path: freebox/app_token
       vault_mount_point: "{{ hashi_short_mount_point }}"