---
- name: Valide les inputs du role user
  import_tasks: validation_input.yml

- name: création du groupe
  become: true
  become_method: "{{ custom_become_method }}"
  group:
    name: "{{ user_group }}"
    gid: "{{ user_gid }}"
    state: present
  when: user_group is not none
  notify: user_changed_on_system

- name: création de l'utilisateur
  become: true
  become_method: "{{ custom_become_method }}"
  user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    home: "{{ user_home | default(omit) }}"
    uid: "{{ user_uid }}"
    shell: "{{ user_shell }}"
    comment: "{{ user_comment }}"
    append: true
    groups: "{{ user_groups }}"
    expires: "{{ user_expires }}"
  when: user_name is not none
  notify: user_changed_on_system

- name: lecture du "max password age" de l'utilisateur
  become: true
  become_method: "{{ custom_become_method }}"
  shell: |
    set -o pipefail
    export LANG=en_US.UTF-8
    chage -l {{ user_name | quote }} | grep "^Maximum number of days between password change" | sed 's/.*: //'
  when: user_name is not none
  register: user_current_max_pwd_age
  changed_when: false

- name: définition du "max password age" de l'utilisateur
  become: true
  become_method: "{{ custom_become_method }}"
  command: chage -M {{ user_password_expires | default(-1) }} {{ user_name }}
  when:
    - user_name is not none
    - user_current_max_pwd_age.stdout|string != user_password_expires|default(-1)|string
    - not user_current_max_pwd_age.skipped|default('false')|bool

- name: unlock caccia user
  become: true
  become_method: "{{ custom_become_method }}"
  command: "{{ user_caccia_bin_path }} -u {{ user_name }}"
  when: user_name is not none and user_unlock_caccia