---
- name: Add ifconfig package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    state: present
    name: net-tools

- name: Rename interface
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.lineinfile:
    path: "{{ proxmox_network_interface_path }}"
    regexp: '^iface .* inet manual'
    line: "face {{ proxmox_interface_custom_name}} inet manual"
  notify: proxmox_need_reboot

- name: Get interface mac adress
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.shell: "ip a | grep vmbr0: -A 1  | grep -o -E ..:..:..:..:..:..  | head -n 1"
  register: proxmox_mac_address

- name: Fix interface bridge name
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.lineinfile:
    path: "{{ proxmox_network_interface_path }}"
    regexp: 'bridge-ports .*'
    line: "bridge-ports {{ proxmox_interface_custom_name}}"
  notify: proxmox_need_reboot

- name: Template config file
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ proxmox_templates }}"
  notify: proxmox_need_reboot