---
- name: Add debian package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    state: present
    name: xfsprogs

- name: Add the xfs module
  become: true
  become_method: "{{ custom_become_method }}"
  community.general.modprobe:
    name: xfs
    state: present