---
- name: import elastic gpg key
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add repo for elk
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present

- name: add debian package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    state: present
    name: xfsprogs

- name: Add the xfs module
  become: true
  become_method: "{{ custom_become_method }}"
  community.general.modprobe:
    name: xfs
    state: present