---
- name: Import gpg key
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
    validate_certs: false
  loop: "{{ prepare_gpg_key }}"

- name: Add custom yum repo
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  loop: "{{ prepare_yum_repo }}"

- name: Disable SELinux
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.posix.selinux:
    state: disabled