---
- name: Import elastic gpg key
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ prepare_gpg_key }}"

- name: Add repo for elk
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.apt_repository:
    repo: "deb {{ item }}"
    state: present
  loop: "{{ prepare_deb}}"

- name: Add debian package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    state: present
    name: xfsprogs

- name: Add the xfs module
  become: true
  become_method: "{{ custom_become_method }}"
  community.general.modprobe:
    name: xfs
    state: present