---
- name: Fix hosts templates
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install required package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    name: "{{ package_to_install}}"
    state: present

- name: Remove useless / unwanted package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    name: "{{ package_to_remove }}"
    state: absent

- ansible.builtin.import_tasks: install_fedora.yml
  when: ansible_distribution == 'Fedora'

- ansible.builtin.import_tasks: install_ubuntu.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Set a hostname
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.hostname:
    name: "{{ ansible_host }}"

- name: set swapiness
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: set max file
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.posix.sysctl:
    name: fs.file-max
    value: '9223372036854775807'
    state: present