---

- name: Fix hosts templates
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install required package
  become: true
  become_method: "{{ custom_become_method }}"
  package:
    name: "{{ package_to_install}}"
    state: present

- name: Remove useless / unwanted package
  become: true
  become_method: "{{ custom_become_method }}"
  package:
    name: "{{ package_to_remove }}"
    state: absent

- import_tasks: install_fedora.yml
  when: ansible_distribution == 'Fedora'

- import_tasks: install_debian.yml
  when: ansible_distribution == 'Debian'

- name: Set a hostname
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.hostname:
    name: "{{ local_dns }}"
