---

- name: Install required package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ package_to_install}}"

- name: Remove useless / unwanted package
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.package:
    name: "{{ package_to_remove }}"
    state: absent

- name: Add the xfs module
  become: true
  become_method: "{{ custom_become_method }}"
  community.general.modprobe:
    name: xfs
    state: present

- name: Set a hostname
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.hostname:
    name: "{{ ansible_host }}"

- name: set swapiness
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: set max file
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.posix.sysctl:
    name: fs.file-max
    value: '9223372036854775807'
    state: present