---
- name: restart elasticsearch
  throttle: 1
  become: true
  systemd:
    name: elasticsearch
    state: restarted
    enabled: true
    daemon_reload: true
  listen: elasticsearch_need_restart

- name: wait elasticsearch port
  wait_for:
    port: "{{ elasticsearch_port }}"
  listen: elasticsearch_need_restart