---

# Utilisation du rpm provenant de digit
haproxy_service_overwrite: false

# Version de haproxy à installer
# A surcharger si utilisation de haproxy-2.4.4
haproxy_package: haproxy-2.0.7

# Version de socat à installer
haproxy_socat_package: socat-1.7.2.2

# Le répertoire de log de HAproxy
haproxy_log_dir: "/var/log/haproxy"

#Le répertoire des fichiers de configuration haproxy
haproxy_config_folder: "/etc/haproxy"
# Fichier de configuration par défaut
haproxy_config_file: "{{ haproxy_config_folder }}/haproxy.cfg"
# Fichiers template de configuration haproxy à déployer
haproxy_templates:
  - src: "haproxy_basic_config.j2"
    dest: "{{ haproxy_config_file }}"
    mode: "640"
    owner: "haproxy"
    group: "haproxy"

haproxy_templates_filedest: "{{ haproxy_templates | map(attribute='dest') | list }}"
# Fichiers template pour la configuration logrotate haproxy
haproxy_logrotate_template:
  - src: "logrotate_haproxy.j2"
    dest: "/etc/logrotate.d/haproxy"
    mode: "640"
    owner: "root"
    group: "root"

# configuration logrotate haproxy
haproxy_logrotate_max_size: 1G

# Fichiers template pour la configuration syslog haproxy
haproxy_rsyslog_template:
  - src: "rsyslog_haproxy.conf.j2"
    dest: "/etc/rsyslog.d/haproxy.conf"
    mode: "640"
    owner: "root"
    group: "root"

# Liste des ports à débloquer dans iptables
haproxy_iptables_ports:
  - port: 80

# Configuration des error files
haproxy_error_files_dest: "{{ haproxy_config_folder}}/errorfiles"
haproxy_error_files: []
#   - file_name: "503.html"
#     src: "haproxy/504.html"
#     code: "503"
#     dest: "{{ haproxy_config_folder}}/errorfiles"

# Configurations additionnelles pour haproxy
haproxy_config_files: []
#  - src: ""
#    dest: ""
#    owner: "" # default: root
#    group: "" # default: root
#    mode: ""  # default: 600

haproxy_additional_config_dirs: []
#  - path: ""
#    owner: "" # default: root
#    group: "" # default: root
#    mode: ""  # default: 600

# Configurer le ssl
haproxy_ssl_enabled: false

# Les sources SSL
haproxy_ssl_certificates: []
#  - dest: "/etc/ssl/certs/haproxy_{{ ansible_host }}.pem"
#    cert: "{{ lookup('files', 'inventory/'~ env ~ '/files/' ~ item.name ~ '.pem') }}"
#    key: "{{ ssl_private_keys[ansible_host] }}"
#    owner: "" # default: root
#    group: "" # default: root
#    mode: ""  # default: 600
#    cert_file: "" # Fichier du certificat (si définit à la place de cert, le certificat sera récupéré depuis le fichier distant)
#    key_file: "" # Fichier du la clé (si définit à la place de key, le certificat sera récupéré depuis le fichier distant)

# Haproxy binary
haproxy_bin: "/opt/haproxy/sbin/haproxy"

# PID files
haproxy_pid_file: "/var/run/haproxy.pid"

# Start options
haproxy_start_option: "-Ws"

##################################
## Variables template par défaut##
##################################
haproxy_template_options:
    - "httplog"
    - "dontlognull"
    - "redispatch"
    - "forwardfor"
    - "log-separate-errors"
haproxy_template_timeouts:
    - "http-request    10s"
    - "queue           1m"
    - "connect         5s"
    - "client          50s"
    - "server          50s"
    - "http-keep-alive 10s"
    - "check           10s"
haproxy_template_retries: 3
haproxy_template_maxconn: 1024
haproxy_template_stat_socket_enabled: true
haproxy_template_ssl_bind_ciphers:
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDH-ECDSA-AES256-GCM-SHA384"
    - "ECDH-RSA-AES256-GCM-SHA384"
    - "ECDHE-ECDSA-AES128-GCM-SHA256"
    - "ECDHE-RSA-AES128-GCM-SHA256"
    - "ECDH-ECDSA-AES128-GCM-SHA256"
    - "ECDH-RSA-AES128-GCM-SHA256"
    - "DHE-RSA-AES128-GCM-SHA256"
    - "ECDHE-ECDSA-AES256-SHA384"
    - "ECDHE-RSA-AES256-SHA384"
    - "ECDH-ECDSA-AES256-SHA384"
    - "ECDH-RSA-AES256-SHA384"
    - "ECDHE-ECDSA-AES256-CCM"
    - "ECDHE-ECDSA-AES256-CCM8"
    - "ECDHE-ECDSA-AES128-SHA256"
    - "ECDHE-ECDSA-AES128-CCM"
    - "ECDHE-ECDSA-AES128-CCM8"
    - "ECDH-ECDSA-AES128-SHA256"
    - "ECDHE-RSA-AES128-SHA256"
    - "ECDH-RSA-AES128-SHA256"
    - "DHE-RSA-AES256-SHA256"
    - "DHE-RSA-AES256-CCM"
    - "DHE-RSA-AES256-CCM8"
    - "DHE-RSA-AES128-SHA256"
    - "DHE-RSA-AES128-CCM"
    - "DHE-RSA-AES128-CCM8"
    - "DH-RSA-AES256-GCM-SHA384"
    - "DH-RSA-AES128-GCM-SHA256"
    - "AES256-GCM-SHA384"
    - "AES128-GCM-SHA256"
    - "DH-RSA-AES256-SHA256"
    - "DH-RSA-AES128-SHA256"
    - "AES256-SHA256"
    - "AES128-SHA256"
    - "AES256-CCM"
    - "AES128-CCM"
    - "AES256-CCM8"
    - "AES128-CCM8"
    - "DHE-PSK-CHACHA20-POLY1305"
    - "DHE-RSA-AES256-GCM-SHA384"
    - "DHE-RSA-CHACHA20-POLY1305"
    - "ECDHE-ECDSA-CHACHA20-POLY1305"
    - "ECDHE-PSK-CHACHA20-POLY1305"
    - "ECDHE-RSA-CHACHA20-POLY1305"
    - "PSK-CHACHA20-POLY1305"
    - "RSA-PSK-CHACHA20-POLY1305"
haproxy_template_ssl_bind_options:
    - "no-sslv3"
    - "no-tlsv10"
    - "no-tlsv11"
    - "no-tls-tickets"
## https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Security-Policy
# haproxy_template_csp: [] pour désactiver les csp
haproxy_template_csp:
    - "default-src 'self'"
#   - "script-src 'self'"
haproxy_template_frame_options: "sameorigin"
haproxy_template_strict_transport_security_max_age: "15552000"
haproxy_template_ssl_cert: "{% if haproxy_ssl_certificates %}{{ haproxy_ssl_certificates[0].dest }}{% endif %}"
haproxy_template_default_dh_param: 2048
haproxy_template_bind_ip: "0.0.0.0"
haproxy_template_log_format: "%ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %sslv\ %sslc\ %{+Q}r"
haproxy_template_valid_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
    - "HEAD"
    - "PUT"
    - "DELETE"
haproxy_template_backend_name: "app"
haproxy_template_backend_ip: "localhost"
haproxy_template_backend_port: "8080"

haproxy_state: started
