---
haproxy_owner: haproxy
haproxy_group: haproxy

haproxy_custom_dirs:
  - path: /run/haproxy
    state: directory
    owner: "{{ haproxy_owner}}"
    group: "{{ haproxy_group}}"
    mode: "0755"

haproxy_packages:
  - haproxy

haproxy_templates:
  - src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0640"
    owner: "{{ haproxy_owner }}"
    group: "{{ haproxy_group }}"

haproxy_stats_user: admin
haproxy_stats_password: "{{ lookup('hashi_vault', hashi_haproxy_path ~ '/stats_user:moz ' ~ hashi_connect) }}"

haproxy_filesystem_list:
  - lv: lv_haproxy_log
    vg: "{{ custom_vg_name }}"
    size: 1g
    path: /var/log/haproxy
    owner: "{{ haproxy_owner }}"
    group: "{{ haproxy_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

haproxy_template_options:
  - httplog
  - dontlognull
  - redispatch
  - forwardfor
  - log-separate-errors

haproxy_template_timeouts:
  - http-request    10s
  - queue           1m
  - connect         5s
  - client          50s
  - server          50s
  - http-keep-alive 10s
  - check           10s

haproxy_certs_path: /etc/haproxy

ssl_minimal_file:
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
    dest: "{{ haproxy_certs_path }}/cert.pem"
    user: "{{ haproxy_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    dest: "{{ haproxy_certs_path }}/chain.pem"
    user: "{{ haproxy_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    dest: "{{ haproxy_certs_path }}/fullchain.pem"
    user: "{{ haproxy_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: "{{ haproxy_certs_path }}/privkey.pem"
    user: "{{ haproxy_owner }}"
  - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    dest: "{{ haproxy_certs_path }}/fullchain.pem.key"
    user: "{{ haproxy_owner }}"