---
hddtemp_package:
  - hddtemp
  - pip

hddtemp_custom_templates:
  - src: hddtemp.service.j2
    dest: /etc/systemd/system/hddtemp.service
    mode: "0640"
  - src: hddtemp.py.j2
    dest: /usr/bin/hddtemp_server
    mode: "0700"