---

- name: LVM vg | Récuperation informations sur les LVM pv
  become: true
  shell: pvs --reportformat json
  register: filesystem_pvs_raw

- name: LVM vg | travail sur chaque LVM vg
  include_tasks: each/lvm_vg_create_extend.yml
  loop: "{{ filesystem_lvm_vg_list }}"
  loop_control:
    loop_var: lvm_vg_item

