---

- name: LVM lv | check if lv already exist
  stat:
    path: "/dev/{{ item.vg }}/{{ item.lv }}"
    follow: yes
  loop: "{{ filesystem_list }}"

- name: LVM lv | Create / Resize Filesystem
  become: true
  lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    size: "{{ item.size }}"
    shrink: "{{ item.shrink|default('no') }}"
    force: "{{ item.force|default('no') }}"
  loop: "{{ filesystem_list }}"

- name: LVM lv | format or extend fs
  become: true
  filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/{{ item.vg }}/{{ item.lv }}"
    resizefs: "{{ item.resizefs | default('yes') }}"
    force: no
  loop: "{{ filesystem_list }}"

- name: LVM lv fs | change MetaData
  become: true
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  when: item.owner is defined
  loop: "{{ filesystem_list }}"
