---
- name: Restart cosmos_node_factory Node
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: cosmos_node_factory
    state: restarted
    enabled: true
    daemon_reload: true
  listen: cosmos_node_factory_need_restart