---
grafana_repo:
  - name : grafana-enterprise
    description: Miroir du repo officiel de Grafana
    baseurl: https://rpm.grafana.com
    file: grafana
    gpgcheck: false
    state: present
    enabled: true

grafana_custom_configs:
  - src: grafana/grafana.ini.j2
    dest: /etc/grafana/grafana.ini

grafana_data_dir: /var/lib/grafana
grafana_log_dir: /var/log/grafana

grafana_admin_user: admin

grafana_filesystem_list:
  - lv: lv_grafana_data
    vg: fedora_fedora
    size: 1G
    path: "{{ grafana_data_dir }}"
    owner: grafana
    group: grafana
    mode: "0750"
    fstype: "{{ filesystem_type | default('xfs') }}"
    force: false
    shrink: false
  - lv: lv_grafana_log
    vg: fedora_fedora
    size: 500M
    path: "{{ grafana_log_dir }}"
    owner: grafana
    group: grafana
    mode: "0750"
    fstype: "{{ filesystem_type | default('xfs') }}"
    force: false
    shrink: false

grafana_custom_packages:
  - nss
  - gtk3
#  - libXScrnSaver TODO : pour fresh install, installer cette dep à la main (ou fix erreur ansible)

ssl_minimal_file:
 - src: "/etc/letsencrypt/live/{{ ansible_host }}/cert.pem"
   dest: /etc/grafana/cert.pem
   user: grafana
 - src: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
   dest: /etc/grafana/chain.pem
   user: grafana
 - src: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
   dest: /etc/grafana/fullchain.pem
   user: grafana
 - src: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
   dest: /etc/grafana/privkey.pem
   user: grafana

