---

subspace_owner: chimera
subspace_group: chimera

subspace_donwload_binary: true

subspace_install_path: /opt/chimera
subspace_github_url: https://github.com/subspace/subspace/releases/download
subpsace_snapshot: gemini-3f-2023-aug-22
subspace_logrotate_folder: /etc/logrotate.d


subspace_node_install_enabled: true
subspace_node_install_path: "{{ subspace_install_path }}/node"
subspace_node_binary_url: "{{ subspace_github_url }}/{{ subpsace_snapshot }}/subspace-node-ubuntu-x86_64-v2-{{ subpsace_snapshot}}"
subspace_node_binary_path: "/usr/bin/{{ subspace_node_binary_name}}"
subspace_node_binary_name: subspace_node
subspace_node_logrotate_file: subspace_node
subspace_node_templates:
  - src: subspace_node.service.j2
    dest: /etc/systemd/system/subspace_node.service
    mode: "0640"
  - src: subspace_node.j2
    dest: "{{ subspace_logrotate_folder }}/{{ subspace_node_logrotate_file }}"
subspace_node_log_file: node.log
subspace_node_log_folder: /var/log/chimera/subspace_node
subspace_node_directories:
  - path: "{{ subspace_node_install_path }}"
  - path: "{{ subspace_node_log_folder }}"
subspace_node_filesystem_list:
  - lv: lv_chimera_base
    vg: "{{ custom_vg_name }}"
    size: 10g
    path: "{{ subspace_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - lv: lv_subspace_node_log
    vg: "{{ custom_vg_name }}"
    size: 2g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

subspace_farmer_install_enabled: true
subspace_farmer_binary_url: "{{ subspace_github_url }}/{{ subpsace_snapshot }}/subspace-farmer-ubuntu-x86_64-skylake-{{ subpsace_snapshot}}"
subspace_farmer_install_path: "{{ subspace_install_path }}/farmer"
subspace_farmer_binary_path: "/usr/bin/{{ subspace_farmer_binary_name}}"
subspace_farmer_binary_name: subspace_farmer
subspace_farmer_logrotate_file: subspace_farmer
subspace_farmer_templates:
  - src: subspace_farmer.service.j2
    dest: /etc/systemd/system/subspace_farmer.service
    mode: "0640"
  - src: subspace_farmer.j2
    dest: "{{ subspace_logrotate_folder }}/{{ subspace_farmer_logrotate_file }}"
subspace_farmer_log_file: farmer.log
subspace_farmer_log_folder: /var/log/chimera/subspace_farmer
subspace_farmer_wallet_adress: "{{ lookup('hashi_vault', hashi_subspace_path ~ '/wallet:moz ' ~ hashi_connect) }}"
subspace_farmer_directories:
  - path: "{{ subspace_farmer_install_path }}"
  - path: "{{ subspace_farmer_log_folder }}"
subpace_farmer_plot_size: 60g

subspace_farmer_filesystem_list:
  - lv: lv_subspace_farmer_log
    vg: "{{ custom_vg_name }}"
    size: 2g
    path: "{{ subspace_farmer_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false


subspace_extra_package:
  - libgomp1
  - nginx
  - logrotate
