---
subspace_owner: chimera
subspace_group: chimera

subspace_donwload_binary: true

subspace_install_path: "/opt/chimera_{{ subspace_owner }}"
subspace_github_url: https://github.com/subspace/subspace/releases/download
subpsace_snapshot: gemini-3e-2023-jul-03

subspace_node_install_path: "{{ subspace_install_path }}/node"
subspace_node_binary_url: "{{ subspace_github_url }}/{{ subpsace_snapshot }}/subspace-node-ubuntu-x86_64-v2-{{ subpsace_snapshot}}"
subspace_node_binary_path: "/usr/bin/{{ subspace_node_binary_name}}"
subspace_node_binary_name: subspace_node
subspace_node_templates:
  - src: subspace_node.service.j2
    dest: /etc/systemd/system/subspace_node.service
    mode: "0640"


subspace_farmer_binary_url: "{{ subspace_github_url }}/{{ subpsace_snapshot }}/subspace-farmer-ubuntu-x86_64-skylake-{{ subpsace_snapshot}}"
subspace_farmer_install_path: "{{ subspace_install_path }}/farmer"
subspace_farmer_binary_path: "/usr/bin/{{ subspace_farmer_binary_name}}"
subspace_farmer_binary_name: subspace_farmer
subspace_farmer_templates:
  - src: subspace_farmer.service.j2
    dest: /etc/systemd/system/subspace_farmer.service
    mode: "0640"

subspace_wallet_adress: "{{ lookup('hashi_vault', hashi_subspace_path ~ '/wallet:moz ' ~ hashi_connect) }}"


subspace_filesystem_list:
  - lv: lv_chimera_base
    vg: "{{ custom_vg_name }}"
    size: 10g
    path: "{{ subspace_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false


subspace_extra_package:
  - libgomp1
  - nginx

subspace_directories:
  - path: "{{ subspace_node_install_path }}"
  - path: "{{ subspace_farmer_install_path }}"

