---

- name: List key from node
  ansible.builtin.shell: babylon --home {{ babylon_home }} keys list
  changed_when: false
  register: babylon_key_list

- name: DEBUG
  ansible.builtin.debug:
    msg:{{ babylon_key_list }}

- name: Run babylon command with password and confirmation
  expect:
    command: babylon --log_format json --home {{ babylon_home }} keys add {{ babylon_key_name }}
    responses:
      "Enter keyring passphrase .*": "{{ babylon_key_password }}"
      "Re-enter keyring passphrase .*": "{{ babylon_key_password }}"
  register: babylon_output
  delegate_to: localhost
  args:
    echo: true

- name: Extract last list of words
  set_fact:
    mnemonic_phrase: "{{ babylon_output.stdout | regex_findall('.*Important\\*\\* (.*)') | last }}"
  when: babylon_output.stdout is search('.*Important\\*\\* .*')

- name: Display extracted mnemonic phrase
  debug:
    var: mnemonic_phrase