---

- name: Install binaries for Babylon
  become: true
  become_method: "{{ custom_become_method }}"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ babylon_packages }}"

- name: Create directory
  become: true
  become_method: "{{ custom_become_method }}"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(babylon_owner) }}"
    group: "{{ item.group | default(babylon_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ babylon_directories }}"