---

prepare_gpg_key:
  - https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - https://packages.grafana.com/gpg.key

prepare_yum_repo:
  - src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
  - src: grafana.repo
    dest: /etc/yum.repos.d/elastic.repo

prepare_deb:
  - https://artifacts.elastic.co/packages/8.x/apt stable main
  - https://packages.grafana.com/oss/deb stable main
  - https://packages.grafana.com/enterprise/deb stable main
