---
- name: Restart Juno Node
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: juno_node
    state: restarted
    enabled: true
    daemon_reload: true
  listen: juno_node_need_restart