---
- name: restart kibana
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: kibana
    state: restarted
    enabled: true
    daemon_reload: true
  listen: kibana_need_restart
