---
juno_node_owner: juno
juno_node_group: juno

juno_node_path: /opt/juno_node

juno_node_filesystem_list:
  - lv: lv_juno_node
    vg: "{{ custom_vg_name }}"
    size: 250g
    path: "{{ juno_node_path}}"
    owner: "{{ juno_node_owner }}"
    group: "{{ juno_node_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

juno_node_templates:
  - src: juno_node.service.j2
    dest: /etc/systemd/system/juno_service.service
    mode: "0640"
    owner: "{{ juno_node_owner }}"
    group: "{{ juno_node_group }}"
  - src: profile.j2
    dest: /home/juno/.profiles
    mode: "0640"
    owner: "{{ juno_node_owner }}"
    group: "{{ juno_node_group }}"