---
- name: restart haproxy
  become: true
  become_method: "{{ custom_become_method }}"
  systemd:
    name: haproxy_service_name
    state: restarted
    enabled: true
    daemon_reload: true
  listen: haproxy_need_restart