---
- import_tasks: install.yml

- import_tasks: config.yml

- include_tasks: ssl.yml

- name: Force restart if needed
  meta: flush_handlers

- include_tasks: bootstrap.yml

- include_tasks: roles.yml

- include_tasks: users.yml

- name: Force restart if needed
  meta: flush_handlers

