---
- import_tasks: install.yml

- import_tasks: config.yml

- include_tasks: ssl.yml

- name: Force le restart si necessaire
  meta: flush_handlers

- include_tasks: param-default-password.yml

- include_tasks: param-change-password.yml

- name: Force le restart si necessaire
  meta: flush_handlers

