---
- name: Ajoute les rôles
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/role/{{ item.name }}"
    method: POST
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ item.content }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_items: "{{ elasticsearch_plugin_xpack_roles_files }}"
  no_log: "{{ elasticsearch_no_log_enabled }}"

- name: Ajoute les role_mappings
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/role_mapping/{{ item.name }}"
    method: POST
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ item.content }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_items: "{{ elasticsearch_plugin_xpack_role_mappings_files }}"
  no_log: "{{ elasticsearch_no_log_enabled }}"

- name: Ajoute les utilisateurs
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/user/{{ item.name }}"
    method: POST
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ item.content }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_items: "{{ elasticsearch_plugin_xpack_users_files }}"
  no_log: "{{ elasticsearch_no_log_enabled }}"
