---
- name: Change les passwords des users additionnels
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/user/{{ item.name }}/_password"
    method: PUT
    user: "{{ elasticsearch_elastic_user }}"
    password: "{% if elasticsearch_elastic_current_password is none %}{{ elasticsearch_elastic_password }}{% else %}{{ elasticsearch_elastic_current_password }}{% endif %}"
    body:
      password: "{{ item.password }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  changed_when: false
  no_log: "{{ elasticsearch_no_log_enabled }}"
  with_items: "{{ elasticsearch_cluster_users }}"
  when: elasticsearch_cluster_users | length > 0

