---
- name: Verifie que le password elasticsearch_elastic_password est definie
  assert:
    that: elasticsearch_elastic_password is not none
    msg: "Vous n'avez pas positionné de valeur pour la variable elasticsearch_elastic_password. Déploiement arrêté."

- name: verifie si le keystore existe
  become: true
  ansible.builtin.stat:
    path: "{{ elasticsearch_path_config }}/elasticsearch.keystore"
  register: elasticsearch_keystore_check

- name: Cree le elasticsearch keystore
# Ce become affecte toutes les tâches du  block.
  become: true
  block:
  - name: create the keystore if it doesn't exist yet
    command: >
     {{ elasticsearch_path_bin }}/bin/elasticsearch-keystore create
    args:
      creates: "{{ elasticsearch_path_config }}/elasticsearch.keystore"
    environment:
      ES_PATH_CONF: "{{ elasticsearch_path_config }}"
      JAVA_HOME: "{{ elasticsearch_java_home }}"
    when: not elasticsearch_keystore_check.stat.exists

  - name: Check si le bootstrap password est défini
    command: >
     {{ elasticsearch_path_bin }}/bin/elasticsearch-keystore list
    register: list_keystore
    changed_when: False
    environment:
      ES_PATH_CONF: "{{ elasticsearch_path_config }}"
      JAVA_HOME: "{{ elasticsearch_java_home }}"

  - name: Cree le bootstrap password pour le user elastic
    shell: echo "{{ elasticsearch_elastic_password }}"
      | "{{ elasticsearch_path_bin }}"/bin/elasticsearch-keystore add -x 'bootstrap.password'
    when: list_keystore is defined and list_keystore.stdout_lines is defined and 'bootstrap.password' not in list_keystore.stdout_lines
    environment:
      ES_PATH_CONF: "{{ elasticsearch_path_config }}"
      JAVA_HOME: "{{ elasticsearch_java_home }}"
    no_log: "{{ elasticsearch_no_log_enabled }}"
    notify: elasticsearch_need_restart

- name: Active du x-pack
  become: true
  lineinfile:
    path: "{{ elasticsearch_path_config }}/elasticsearch.yml"
    line: "xpack.security.enabled: true"
  when: not elasticsearch_license_enabled
  notify: elasticsearch_need_restart