---
- name: Importe les templates Elasticsearch
  run_once: true
  uri:
    url: "{{ elasticsearch_http_base_url }}/_template/{{ item|basename|regex_replace('\\.json.*\\.j2', '') }}"
    method: PUT
    status_code: [200,201,204]
    body: "{{ lookup('template', item) }}"
    body_format: json
    force_basic_auth: yes
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    timeout: "{{ elasticsearch_max_time_api|default(30) }}"
    validate_certs: no
  loop: "{{ elasticsearch_index_templates }}"
