---
- name: Importe la licence
  run_once: true
  uri:
    url: "{{ elasticsearch_url_license }}?acknowledge=true"
    method: PUT
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ elasticsearch_license_content }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
  register: elasticsearch_import_licence_status
  until: elasticsearch_import_licence_status.status is defined and elasticsearch_import_licence_status.status == 200
  no_log: "{{ elasticsearch_no_log_enabled }}"
  when: not ansible_check_mode

- name: Verifie l'import de la licence
  fail:
    msg: "L'import de la licence Elasticsearch a echoué"
  when: elasticsearch_import_licence_status.stdout is defined and elasticsearch_import_licence_status.stdout not in ["200"]
