---
- name: Add elasticsearch roles
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/role/{{ item.name }}"
    method: POST
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ item.content }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
  loop: "{{ elasticsearch_roles_custom }}"
