---
- name: Copy ssl files
  become: true
  become_method: "{{ custom_become_method }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "{{ item.mode | default('0640') }}"
    remote_src: true
  loop: "{{ ssl_minimal_file }}"
