---
- name: change user password
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/user/{{ item.name }}/_password"
    method: PUT
    user: "{{ elasticsearch_elastic_user }}"
    password: "{% if elasticsearch_elastic_current_password is none %}{{ elasticsearch_elastic_password }}{% else %}{{ elasticsearch_elastic_current_password }}{% endif %}"
    body:
      password: "{{ item.password }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
  changed_when: false
  loop: "{{ elasticsearch_cluster_users }}"
  when: elasticsearch_cluster_users | length > 0

- name: add elasticsearch custom users
  run_once: true
  uri:
    url: "{{ elasticsearch_url_security }}/user/{{ item.name }}"
    method: POST
    user: "{{ elasticsearch_elastic_user }}"
    password: "{{ elasticsearch_elastic_password }}"
    body: "{{ item.content }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
  loop: "{{ elasticsearch_users_custom }}"
