---
metricbeat_elasticsearch_url: "https://cerberus-alpha.mythologic.fr:9200, https://cerberus-beta.mythologic.fr:9200, https://cerberus-gamma.mythologic.fr:9200, https://cerberus-delta.mythologic.fr:9200"


metricbeat_elasticsearch_password: "{{ lookup('auto_pass', 'elasticsearch/metricbeat', key='moz') }}"
metricbeat_elasticsearch_user: metricbeat_olympus