---
- name: Install binaries
  become: true
  become_method: "{{ custom_become_method }}"
  yum:
    name: "{{ hddtemp_package }}"
    state: present
    update_cache: true

- name: Install flask python package
  ansible.builtin.pip:
    name: flask

- name: Template config files
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(hddtemp_user) }}"
    group: "{{ item.group | default(hddtemp_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ hddtemp_custom_templates }}"
  notify:
    - hddtemp_need_restart

