---
babylon_node_owner: babylon
babylon_node_group: babylon

babylon_node_path: /opt/babylon_node
babylon_go_path: "{{ babylon_node_path }}/go"
babylon_home: /home/babylon
babylon_chain_id: bbn-test1
babylon_node_name: "{{ ansible_host }}-babylon"

babylon_genesis_source: https://github.com/babylonchain/networks/raw/main/bbn-test1/genesis.tar.bz2
babylon_genesis_location: "{{ babylon_home}}/.babylond/config/genesis.json"

babylon_config_toml_path: "{{ babylon_home}}/.babylond/config/config.toml"
babylon_app_toml_path: "{{ babylon_home }}/.babylond/config/app.toml"

babylon_seeds: 03ce5e1b5be3c9a81517d415f65378943996c864@18.207.168.204:26656,a5fabac19c732bf7d814cf22e7ffc23113dc9606@34.238.169.221:26656
babylon_persistent_peers: 03ce5e1b5be3c9a81517d415f65378943996c864@18.207.168.204:26656,a5fabac19c732bf7d814cf22e7ffc23113dc9606@34.238.169.221:26656

babylon_tag: bbn0
babylon_network: mainnet

babylon_packages:
  - jq
  - curl
  - snapd
  - git
  - ufw
  - gcc
  - gcc-c++
  - kernel-devel
  - make
  - docker

babylon_node_filesystem_list:
  - lv: lv_babylon_node
    vg: "{{ custom_vg_name }}"
    size: 100g
    path: "{{ babylon_node_path}}"
    owner: "{{ babylon_node_owner }}"
    group: "{{ babylon_node_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

babylon_node_templates:
  - src: babylon_node.service.j2
    dest: /etc/systemd/system/babylon_service.service
    mode: "0640"
    owner: "{{ babylon_node_owner }}"
    group: "{{ babylon_node_group }}"
  - src: profile.j2
    dest: /home/babylon/.profiles
    mode: "0640"
    owner: "{{ babylon_node_owner }}"
    group: "{{ babylon_node_group }}"

babylon_directories:
  - path: "{{ babylon_home }}/.babylond"
  - path: "{{ babylon_home }}/.babylond/cosmovisor"
  - path: "{{ babylon_home }}/.babylond/cosmovisor/genesis"
  - path: "{{ babylon_home }}/.babylond/cosmovisor/genesis/bin"
  - path: "{{ babylon_home }}/.babylond/cosmovisor/upgrades"
  - path: "{{ babylon_node_path }}"
  - path: "{{ babylon_go_path }}"