---
babylon_owner: chimera
babylon_group: chimera

babylon_git_version: v0.7.2

babylon_binaries_download_url: "https://github.com/Tocard/babylon/releases/download/build-{{ babylon_git_version }}/babylond"
babylon_libwasmvm_download_url: "https://github.com/Tocard/babylon/releases/download/build-{{ babylon_git_version }}/libwasmvm.x86_64.so"
babylon_genesis_donwload_url: https://github.com/babylonchain/networks/raw/main/bbn-test-2/genesis.tar.bz2

babylon_log_path: /var/log/chimera/
babylon_log_file: babylon.log
babylon_binaries_path: /usr/bin/
babylon_path: "{{ chimera_base_install_path}}"
babylon_home: "{{ babylon_path }}/babylon"
babylon_chain_id: bbn-test2
babylon_name: "{{ ansible_hostname }}"
babylon_config_path: "{{ babylon_home }}/config"


babylon_genesis_location: "{{ babylon_config_path }}/genesis.json"
babylon_config_toml_path: "{{ babylon_config_path }}/config.toml"
babylon_app_toml_path: "{{babylon_config_path }}/app.toml"

babylon_seeds: "8da45f9ff83b4f8dd45bbcb4f850999637fbfe3b@seed0.testnet.babylonchain.io:26656,4b1f8a774220ba1073a4e9f4881de218b8a49c99@seed1.testnet.babylonchain.io:26656"
babylon_persistent_peers: "8da45f9ff83b4f8dd45bbcb4f850999637fbfe3b@seed0.testnet.babylonchain.io:26656,4b1f8a774220ba1073a4e9f4881de218b8a49c99@seed1.testnet.babylonchain.io:26656"


babylon_tag: bbn2
babylon_network: mainnet

babylon_packages:
  - jq
  - curl
  - snapd
  - git
  - ufw
  - gcc
  - g++
  - make
  - docker
  - build-essential
  - acl


babylon_filesystem_list:
  - lv: lv_chimera
    vg: "{{ custom_vg_name }}"
    size: 200g
    path: "{{ babylon_path}}"
    owner: "{{ babylon_owner }}"
    group: "{{ babylon_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - lv: lv_log_babylon
    vg: "{{ custom_vg_name }}"
    size: 2g
    path: "{{ babylon_log_path }}"
    owner: "{{ babylon_owner }}"
    group: "{{ babylon_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

babylon_templates:
  - src: babylon.service.j2
    dest: /etc/systemd/system/babylon.service
  - src: app.toml.j2
    dest: "{{ babylon_app_toml_path}}"
  - src: config.toml.j2
    dest: "{{ babylon_config_toml_path}}"


babylon_privkey_validator: "{{ lookup('hashi_vault', hashi_babylon_path ~ '/privkey' ~ hashi_connect) }}"
babylon_validator_templates_enabled: true
babylon_validator_templates:
  - src: priv_validator_key.json.j2
    dest: "{{ babylon_config_path}}/priv_validator_key.json"


babylon_directories:
  - path: "{{ chimera_base_install_path }}"
  - path: "{{ babylon_home }}"
  - path: "{{ babylon_config_path }}"
  - path: "{{ babylon_log_path }}"

babylon_keys_management_enabled: false
babylon_key_name: "{{ ansible_hostname }}"
babylon_key_password: "{{ lookup('hashi_vault', hashi_babylon_path ~ '/' ~ ansible_hostname  ~ hashi_connect) }}"
