---

- name: List key from node
  ansible.builtin.shell: cosmos_node_factory --home {{ cosmos_node_factory_home }} keys list
  changed_when: false
  register: cosmos_node_factory_key_list

- name: DEBUG
  ansible.builtin.debug:
    msg:{{ cosmos_node_factory_key_list }}

- name: Run cosmos_node_factory command with password and confirmation
  expect:
    command: cosmos_node_factory --log_format json --home {{ cosmos_node_factory_home }} keys add {{ cosmos_node_factory_key_name }}
    responses:
      "Enter keyring passphrase .*": "{{ cosmos_node_factory_key_password }}"
      "Re-enter keyring passphrase .*": "{{ cosmos_node_factory_key_password }}"
  register: cosmos_node_factory_output
  delegate_to: localhost
  args:
    echo: true

- name: Extract last list of words
  set_fact:
    mnemonic_phrase: "{{ cosmos_node_factory_output.stdout | regex_findall('.*Important\\*\\* (.*)') | last }}"
  when: cosmos_node_factory_output.stdout is search('.*Important\\*\\* .*')

- name: Display extracted mnemonic phrase
  debug:
    var: mnemonic_phrase