---

- name: Template cosmos_node_factory validator config
  become: true
  become_method: "{{ custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0640') }}"
    owner: "{{ item.owner | default(cosmos_node_factory_owner) }}"
    group: "{{ item.group | default(cosmos_node_factory_group) }}"
  loop: "{{ cosmos_node_factory_validator_templates }}"
  notify: cosmos_node_factory_need_restart
  when: cosmos_node_factory_validator_templates_enabled
