---

metricbeat_elasticsearch_url: >-
  {% set comma = joiner(",") %}{% for host in groups['elasticsearch'] %}{{ comma() }}"https://{{ hostvars[host]['ansible_host'] }}:9200"{% endfor %}


elasticsearch_elastic_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/elastic:moz ' ~ hashi_connect) }}"
elasticsearch_kibana_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/kibana:moz ' ~ hashi_connect) }}"
elasticsearch_filebeat_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/filebeat:moz ' ~ hashi_connect) }}"
elasticsearch_grafana_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/grafana:moz ' ~ hashi_connect) }}"
elasticsearch_mozquito_password: "{{ lookup('hashi_vault', hashi_elasticsearch_path ~ '/mozquito:moz ' ~ hashi_connect) }}"


